apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Parky
  annotations:
    github.com/project-slug: BelminMahic/Parky
spec:
  type: website
  lifecycle: experimental
  owner: guests
